[build]
  command = "themefisher/academia-hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "themefisher/academia-hugo"

[context.branch-deploy]
  command = "themefisher/academia-hugo"
