[build]
  command = "academia-hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "academia-hugo"

[context.branch-deploy]
  command = "academia-hugo"
